/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author MAX COMPUTERS
 */
public class CrearPlacaMadre extends javax.swing.JFrame {

    /**
     * Creates new form CrudProcesador
     */

    public CrearPlacaMadre() {
        initComponents();
    }

    public JButton getBtnCrearplacam() {
        return btnCrearplacam;
    }

    public void setBtnCrearplacam(JButton btnCrearplacam) {
        this.btnCrearplacam = btnCrearplacam;
    }

    
    public JToggleButton getBtAtrascrea() {
        return btAtrascrea;
    }

    public void setBtAtrascrea(JToggleButton btAtrascrea) {
        this.btAtrascrea = btAtrascrea;
    }


    public JButton getBtncargaplaca() {
        return btncargaplaca;
    }

    public void setBtncargaplaca(JButton btncargaplaca) {
        this.btncargaplaca = btncargaplaca;
    }

    public JComboBox<String> getCbproveedorplaca() {
        return cbproveedorplaca;
    }

    public void setCbproveedorplaca(JComboBox<String> cbproveedorplaca) {
        this.cbproveedorplaca = cbproveedorplaca;
    }

    public JLabel getLbIdcreaplaca() {
        return lbIdcreaplaca;
    }

    public void setLbIdcreaplaca(JLabel lbIdcreaplaca) {
        this.lbIdcreaplaca = lbIdcreaplaca;
    }

    public JLabel getLbplacaimg() {
        return lbplacaimg;
    }

    public void setLbplacaimg(JLabel lbplacaimg) {
        this.lbplacaimg = lbplacaimg;
    }

    public JSpinner getSpMaximoramplaca() {
        return spMaximoramplaca;
    }

    public void setSpMaximoramplaca(JSpinner spMaximoramplaca) {
        this.spMaximoramplaca = spMaximoramplaca;
    }

    public JTextField getTxttiporamcreaplaca() {
        return txttiporamcreaplaca;
    }

    public void setTxttiporamcreaplaca(JTextField txttiporamcreaplaca) {
        this.txttiporamcreaplaca = txttiporamcreaplaca;
    }

    public JSpinner getSpwattsramplaca() {
        return spwattsramplaca;
    }

    public void setSpwattsramplaca(JSpinner spwattsramplaca) {
        this.spwattsramplaca = spwattsramplaca;
    }

    public JTextField getTxtformatocreaplaca2() {
        return txtformatocreaplaca2;
    }

    public void setTxtformatocreaplaca2(JTextField txtformatocreaplaca2) {
        this.txtformatocreaplaca2 = txtformatocreaplaca2;
    }

    public JTextField getTxtmarcacreaplaca() {
        return txtmarcacreaplaca;
    }

    public void setTxtmarcacreaplaca(JTextField txtmarcacreaplaca) {
        this.txtmarcacreaplaca = txtmarcacreaplaca;
    }

    public JTextField getTxtmodelocreaplaca() {
        return txtmodelocreaplaca;
    }

    public void setTxtmodelocreaplaca(JTextField txtmodelocreaplaca) {
        this.txtmodelocreaplaca = txtmodelocreaplaca;
    }

    public JTextField getTxtpreciocreaplaca() {
        return txtpreciocreaplaca;
    }

    public void setTxtpreciocreaplaca(JTextField txtpreciocreaplaca) {
        this.txtpreciocreaplaca = txtpreciocreaplaca;
    }

    public JTextField getTxtpuertosalma() {
        return txtpuertosalma;
    }

    public void setTxtpuertosalma(JTextField txtpuertosalma) {
        this.txtpuertosalma = txtpuertosalma;
    }

    public JTextField getTxtpuertosusb() {
        return txtpuertosusb;
    }

    public void setTxtpuertosusb(JTextField txtpuertosusb) {
        this.txtpuertosusb = txtpuertosusb;
    }

    public JTextField getTxtranuraexpcreaplaca() {
        return txtranuraexpcreaplaca;
    }

    public void setTxtranuraexpcreaplaca(JTextField txtranuraexpcreaplaca) {
        this.txtranuraexpcreaplaca = txtranuraexpcreaplaca;
    }

    public JTextField getTxtsocketcreaplaca() {
        return txtsocketcreaplaca;
    }

    public void setTxtsocketcreaplaca(JTextField txtsocketcreaplaca) {
        this.txtsocketcreaplaca = txtsocketcreaplaca;
    }

    public JTextField getTxtstockcreaplaca() {
        return txtstockcreaplaca;
    }

    public void setTxtstockcreaplaca(JTextField txtstockcreaplaca) {
        this.txtstockcreaplaca = txtstockcreaplaca;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnCrearplacam = new javax.swing.JButton();
        txtsocketcreaplaca = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        spMaximoramplaca = new javax.swing.JSpinner();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lbIdcreaplaca = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtmarcacreaplaca = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtmodelocreaplaca = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtpuertosusb = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btAtrascrea = new javax.swing.JToggleButton();
        jLabel20 = new javax.swing.JLabel();
        btncargaplaca = new javax.swing.JButton();
        lbplacaimg = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtpuertosalma = new javax.swing.JTextField();
        txtranuraexpcreaplaca = new javax.swing.JTextField();
        txtformatocreaplaca2 = new javax.swing.JTextField();
        spwattsramplaca = new javax.swing.JSpinner();
        txtpreciocreaplaca = new javax.swing.JTextField();
        txtstockcreaplaca = new javax.swing.JTextField();
        cbproveedorplaca = new javax.swing.JComboBox<>();
        txttiporamcreaplaca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 212, 250), 3));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        btnCrearplacam.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnCrearplacam.setText("Crear");

        txtsocketcreaplaca.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtsocketcreaplaca.setBorder(null);

        jLabel25.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Tipos Ram:");
        jLabel25.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel26.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Maximo Ram:");
        jLabel26.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        spMaximoramplaca.setFont(new java.awt.Font("Montserrat Thin", 0, 18)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("Proveedor:");
        jLabel27.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel28.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Precio:");
        jLabel28.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel29.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("ID Placa Madre:");
        jLabel29.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lbIdcreaplaca.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lbIdcreaplaca.setText("--");
        lbIdcreaplaca.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel30.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("Marca:");
        jLabel30.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtmarcacreaplaca.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtmarcacreaplaca.setBorder(null);

        jLabel31.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("Modelo:");
        jLabel31.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtmodelocreaplaca.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtmodelocreaplaca.setBorder(null);

        jLabel32.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel32.setText("Puertos almacenamiento:");
        jLabel32.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtpuertosusb.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtpuertosusb.setBorder(null);

        jLabel33.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("Puertos USB:");
        jLabel33.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel34.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("Socket:");
        jLabel34.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 212, 250), 3));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        btAtrascrea.setBackground(new java.awt.Color(255, 255, 255));
        btAtrascrea.setFont(new java.awt.Font("Montserrat Black", 1, 48)); // NOI18N
        btAtrascrea.setForeground(new java.awt.Color(0, 212, 250));
        btAtrascrea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(37, 53, 124));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        jLabel20.setText("Placa Madre");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btAtrascrea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btAtrascrea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btncargaplaca.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btncargaplaca.setText("Cargar Imagen");

        lbplacaimg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel36.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel36.setText("Stock:");
        jLabel36.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel37.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("Ranuras expansión:");
        jLabel37.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel38.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("Watts:");
        jLabel38.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel39.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel39.setText("Formato:");
        jLabel39.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtpuertosalma.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtpuertosalma.setBorder(null);

        txtranuraexpcreaplaca.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtranuraexpcreaplaca.setBorder(null);

        txtformatocreaplaca2.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtformatocreaplaca2.setBorder(null);

        spwattsramplaca.setFont(new java.awt.Font("Montserrat Thin", 0, 18)); // NOI18N

        txtpreciocreaplaca.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtpreciocreaplaca.setBorder(null);

        txtstockcreaplaca.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtstockcreaplaca.setBorder(null);

        cbproveedorplaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        txttiporamcreaplaca.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txttiporamcreaplaca.setBorder(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(412, 412, 412)
                        .addComponent(btnCrearplacam))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel32))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spwattsramplaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbIdcreaplaca, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txtmarcacreaplaca, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txtmodelocreaplaca, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txtpuertosalma, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txtpuertosusb, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txtsocketcreaplaca, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(spMaximoramplaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtranuraexpcreaplaca)
                            .addComponent(txtformatocreaplaca2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txtpreciocreaplaca, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txtstockcreaplaca, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(cbproveedorplaca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txttiporamcreaplaca, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                        .addGap(0, 77, Short.MAX_VALUE)
                        .addComponent(btncargaplaca)
                        .addGap(18, 18, 18)
                        .addComponent(lbplacaimg, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(137, 137, 137))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbIdcreaplaca)
                                .addGap(6, 6, 6)
                                .addComponent(txtmarcacreaplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtmodelocreaplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(txtpuertosalma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(txtpuertosusb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txtsocketcreaplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btncargaplaca)
                                    .addComponent(lbplacaimg, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43)
                        .addComponent(spMaximoramplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtranuraexpcreaplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtformatocreaplaca2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spwattsramplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpreciocreaplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel30)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel31)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel33)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel34)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txttiporamcreaplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(txtstockcreaplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(cbproveedorplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnCrearplacam)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btAtrascrea;
    private javax.swing.JButton btnCrearplacam;
    private javax.swing.JButton btncargaplaca;
    private javax.swing.JComboBox<String> cbproveedorplaca;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbIdcreaplaca;
    private javax.swing.JLabel lbplacaimg;
    private javax.swing.JSpinner spMaximoramplaca;
    private javax.swing.JSpinner spwattsramplaca;
    private javax.swing.JTextField txtformatocreaplaca2;
    private javax.swing.JTextField txtmarcacreaplaca;
    private javax.swing.JTextField txtmodelocreaplaca;
    private javax.swing.JTextField txtpreciocreaplaca;
    private javax.swing.JTextField txtpuertosalma;
    private javax.swing.JTextField txtpuertosusb;
    private javax.swing.JTextField txtranuraexpcreaplaca;
    private javax.swing.JTextField txtsocketcreaplaca;
    private javax.swing.JTextField txtstockcreaplaca;
    private javax.swing.JTextField txttiporamcreaplaca;
    // End of variables declaration//GEN-END:variables
}
