/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author EDU
 */
public class CrearDisipadores extends javax.swing.JFrame {

    /**
     * Creates new form CrearDisipadores
     */
    public CrearDisipadores() {
        initComponents();
    }

    public JButton getBtnCargarI() {
        return btnCargarI;
    }

    public void setBtnCargarI(JButton btnCargarI) {
        this.btnCargarI = btnCargarI;
    }

    public JButton getBtnImagenProducto() {
        return btnImagenProducto;
    }

    public void setBtnImagenProducto(JButton btnImagenProducto) {
        this.btnImagenProducto = btnImagenProducto;
    }

    public JSpinner getSpStock() {
        return spStock;
    }

    public void setSpStock(JSpinner spStock) {
        this.spStock = spStock;
    }

    public JComboBox<String> getCmbVentilador() {
        return cmbVentilador;
    }

    public void setCmbVentilador(JComboBox<String> cmbVentilador) {
        this.cmbVentilador = cmbVentilador;
    }

    public JRadioButton getRbNo() {
        return rbNo;
    }

    public void setRbNo(JRadioButton rbNo) {
        this.rbNo = rbNo;
    }

    public JRadioButton getRbSi() {
        return rbSi;
    }

    public void setRbSi(JRadioButton rbSi) {
        this.rbSi = rbSi;
    }

    public JSpinner getSpPrecio() {
        return spPrecio;
    }

    public void setSpPrecio(JSpinner spPrecio) {
        this.spPrecio = spPrecio;
    }

    public JTextField getTxtsocket() {
        return txtsocket;
    }

    public void setTxtsocket(JTextField txtsocket) {
        this.txtsocket = txtsocket;
    }

    public JTextField getTxtModelo() {
        return txtModelo;
    }

    public void setTxtModelo(JTextField txtModelo) {
        this.txtModelo = txtModelo;
    }

    public JTextField getTxtmarca() {
        return txtmarca;
    }

    public void setTxtmarca(JTextField txtmarca) {
        this.txtmarca = txtmarca;
    }

    public JButton getBtnCrear() {
        return btnCrear;
    }

    public void setBtnCrear(JButton btnCrear) {
        this.btnCrear = btnCrear;
    }

    public JToggleButton getBtAtras2() {
        return btAtras2;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public JTextField getTxtID() {
        return txtID;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        spPrecio = new javax.swing.JSpinner();
        jLabel30 = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        btAtras2 = new javax.swing.JToggleButton();
        cmbVentilador = new javax.swing.JComboBox<>();
        txtModelo = new javax.swing.JTextField();
        rbSi = new javax.swing.JRadioButton();
        rbNo = new javax.swing.JRadioButton();
        jLabel36 = new javax.swing.JLabel();
        spStock = new javax.swing.JSpinner();
        txtsocket = new javax.swing.JTextField();
        btnCargarI = new javax.swing.JButton();
        btnImagenProducto = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 212, 250), 3));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrear.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(0, 0, 0));
        btnCrear.setText("Crear");
        jPanel3.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 150, -1));

        jLabel25.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel25.setText("Precio:");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 120, 40));

        spPrecio.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        spPrecio.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        jPanel3.add(spPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 60, 40));

        jLabel30.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel30.setText("Marca:");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 120, 40));

        txtmarca.setBackground(new java.awt.Color(255, 255, 255));
        txtmarca.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtmarca.setForeground(new java.awt.Color(0, 0, 0));
        txtmarca.setBorder(null);
        jPanel3.add(txtmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 150, 40));

        jLabel31.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel31.setText("Modelo:");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 120, 40));

        jLabel32.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel32.setText("Socket:");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 120, 40));

        jLabel33.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel33.setText("RGB:");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 120, 40));

        jLabel34.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel34.setText("Ventiladores:");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 120, 40));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 212, 250), 3));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(37, 53, 124));
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo.png"))); // NOI18N
        jLabel35.setText("Disipadores");
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 420, 90));

        btAtras2.setBackground(new java.awt.Color(255, 255, 255));
        btAtras2.setFont(new java.awt.Font("Montserrat Black", 1, 48)); // NOI18N
        btAtras2.setForeground(new java.awt.Color(0, 212, 250));
        btAtras2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        jPanel5.add(btAtras2, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 80, 100));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 110));

        cmbVentilador.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        cmbVentilador.setForeground(new java.awt.Color(0, 0, 0));
        cmbVentilador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Numero de ventiladores", "1", "2", "3", " " }));
        jPanel3.add(cmbVentilador, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 150, 40));

        txtModelo.setBackground(new java.awt.Color(255, 255, 255));
        txtModelo.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtModelo.setForeground(new java.awt.Color(0, 0, 0));
        txtModelo.setBorder(null);
        jPanel3.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 150, 40));

        buttonGroup1.add(rbSi);
        rbSi.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        rbSi.setForeground(new java.awt.Color(0, 0, 0));
        rbSi.setText("Si");
        jPanel3.add(rbSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 60, 40));

        buttonGroup1.add(rbNo);
        rbNo.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        rbNo.setForeground(new java.awt.Color(0, 0, 0));
        rbNo.setText("No");
        jPanel3.add(rbNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 60, 40));

        jLabel36.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel36.setText("Stock:");
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 120, 40));

        spStock.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jPanel3.add(spStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 60, 40));

        txtsocket.setBackground(new java.awt.Color(255, 255, 255));
        txtsocket.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtsocket.setForeground(new java.awt.Color(0, 0, 0));
        txtsocket.setBorder(null);
        jPanel3.add(txtsocket, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 150, 40));

        btnCargarI.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnCargarI.setForeground(new java.awt.Color(0, 0, 0));
        btnCargarI.setText("Cargar Imagen");
        jPanel3.add(btnCargarI, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, -1, -1));
        jPanel3.add(btnImagenProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 254, 239));

        jLabel37.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel37.setText("ID:");
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 120, 40));

        txtID.setBackground(new java.awt.Color(255, 255, 255));
        txtID.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtID.setForeground(new java.awt.Color(0, 0, 0));
        txtID.setBorder(null);
        jPanel3.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 150, 40));

        jLabel13.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("_______________");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 150, 20));

        jLabel14.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("_______________");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 150, 20));

        jLabel15.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("_______________");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 150, 20));

        jLabel16.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("_______________");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 150, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btAtras2;
    private javax.swing.JButton btnCargarI;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnImagenProducto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbVentilador;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton rbNo;
    private javax.swing.JRadioButton rbSi;
    private javax.swing.JSpinner spPrecio;
    private javax.swing.JSpinner spStock;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtsocket;
    // End of variables declaration//GEN-END:variables
}
