/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JToggleButton;

/**
 *
 * @author TheBigG
 */
public class CRUD_Productos_JB extends javax.swing.JFrame {

    /**
     * Creates new form CRUD_Productos_JB
     */
    public CRUD_Productos_JB() {  
        initComponents();
        setLocationRelativeTo(null);
    }

    public JButton getBtAgregar() {
        return btAgregar;
    }

    public JButton getBtAlmacenamiento() {
        return btAlmacenamiento;
    }

    public JToggleButton getBtAtras() {
        return btAtras;
    }

    public JButton getBtDisipador() {
        return btDisipador;
    }

    public JButton getBtEliminar() {
        return btEliminar;
    }

    public JButton getBtFuente() {
        return btFuente;
    }

    public JButton getBtGabinete() {
        return btGabinete;
    }

    public JButton getBtModificar() {
        return btModificar;
    }

    public JButton getBtPlacaMadre() {
        return btPlacaMadre;
    }

    public JButton getBtProcesador() {
        return btProcesador;
    }

    public JButton getBtRam() {
        return btRam;
    }

    public JButton getBtReporte() {
        return btReporte;
    }

    public JButton getBtTarjetaGrafica() {
        return btTarjetaGrafica;
    }

    public JButton getBtVentiladores() {
        return btVentiladores;
    }

    public JDialog getJdlgCRUD() {
        return jdlgCRUD;
    }

    public JLabel getLblTitulo() {
        return lblTitulo;
    }

    public JToggleButton getBtAtrasDlg() {
        return btAtrasDlg;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdlgCRUD = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btModificar = new javax.swing.JButton();
        btAgregar = new javax.swing.JButton();
        btReporte = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();
        btAtrasDlg = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btAtras = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        btAlmacenamiento = new javax.swing.JButton();
        btVentiladores = new javax.swing.JButton();
        btProcesador = new javax.swing.JButton();
        btFuente = new javax.swing.JButton();
        btTarjetaGrafica = new javax.swing.JButton();
        btPlacaMadre = new javax.swing.JButton();
        btDisipador = new javax.swing.JButton();
        btGabinete = new javax.swing.JButton();
        btRam = new javax.swing.JButton();

        jdlgCRUD.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jdlgCRUD.setResizable(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 212, 250), 3));

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(37, 53, 124));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        lblTitulo.setText("Gestionar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btModificar.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        btModificar.setForeground(new java.awt.Color(0, 0, 0));
        btModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JB/editar.png"))); // NOI18N
        btModificar.setText("Modificar");

        btAgregar.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        btAgregar.setForeground(new java.awt.Color(0, 0, 0));
        btAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JB/agregar.png"))); // NOI18N
        btAgregar.setText("Agregar");

        btReporte.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        btReporte.setForeground(new java.awt.Color(0, 0, 0));
        btReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JB/reporte.png"))); // NOI18N
        btReporte.setText("Reporte");

        btEliminar.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        btEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JB/eliminar.png"))); // NOI18N
        btEliminar.setText("Eliminar");

        btAtrasDlg.setBackground(new java.awt.Color(255, 255, 255));
        btAtrasDlg.setFont(new java.awt.Font("Montserrat Black", 1, 48)); // NOI18N
        btAtrasDlg.setForeground(new java.awt.Color(0, 212, 250));
        btAtrasDlg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N

        javax.swing.GroupLayout jdlgCRUDLayout = new javax.swing.GroupLayout(jdlgCRUD.getContentPane());
        jdlgCRUD.getContentPane().setLayout(jdlgCRUDLayout);
        jdlgCRUDLayout.setHorizontalGroup(
            jdlgCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jdlgCRUDLayout.createSequentialGroup()
                .addGroup(jdlgCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jdlgCRUDLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(jdlgCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jdlgCRUDLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btAtrasDlg, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jdlgCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        jdlgCRUDLayout.setVerticalGroup(
            jdlgCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlgCRUDLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jdlgCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jdlgCRUDLayout.createSequentialGroup()
                        .addComponent(btReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btAtrasDlg))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png")).getImage());
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 212, 250), 3));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(37, 53, 124));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        jLabel2.setText("COMPONENTES");

        btAtras.setBackground(new java.awt.Color(255, 255, 255));
        btAtras.setFont(new java.awt.Font("Montserrat Black", 1, 48)); // NOI18N
        btAtras.setForeground(new java.awt.Color(0, 212, 250));
        btAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 212, 250), 5));

        btAlmacenamiento.setFont(new java.awt.Font("Montserrat", 1, 22)); // NOI18N
        btAlmacenamiento.setForeground(new java.awt.Color(37, 53, 124));
        btAlmacenamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JB/ssd.png"))); // NOI18N
        btAlmacenamiento.setText("Almacenamiento");
        btAlmacenamiento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btVentiladores.setFont(new java.awt.Font("Montserrat", 1, 22)); // NOI18N
        btVentiladores.setForeground(new java.awt.Color(37, 53, 124));
        btVentiladores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JB/ventilador.png"))); // NOI18N
        btVentiladores.setText("Ventiladores");
        btVentiladores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btProcesador.setFont(new java.awt.Font("Montserrat", 1, 22)); // NOI18N
        btProcesador.setForeground(new java.awt.Color(37, 53, 124));
        btProcesador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JB/upc (1).png"))); // NOI18N
        btProcesador.setText("Procesadores");
        btProcesador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btFuente.setFont(new java.awt.Font("Montserrat", 1, 22)); // NOI18N
        btFuente.setForeground(new java.awt.Color(37, 53, 124));
        btFuente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JB/fuente-de-alimentacion.png"))); // NOI18N
        btFuente.setText("Fuentes de Poder");
        btFuente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btTarjetaGrafica.setFont(new java.awt.Font("Montserrat", 1, 22)); // NOI18N
        btTarjetaGrafica.setForeground(new java.awt.Color(37, 53, 124));
        btTarjetaGrafica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JB/tarjeta-de-video.png"))); // NOI18N
        btTarjetaGrafica.setText("Tarjetas Graficas");
        btTarjetaGrafica.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btPlacaMadre.setFont(new java.awt.Font("Montserrat", 1, 22)); // NOI18N
        btPlacaMadre.setForeground(new java.awt.Color(37, 53, 124));
        btPlacaMadre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JB/tarjeta-madre.png"))); // NOI18N
        btPlacaMadre.setText("Placas Madre");
        btPlacaMadre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btDisipador.setFont(new java.awt.Font("Montserrat", 1, 22)); // NOI18N
        btDisipador.setForeground(new java.awt.Color(37, 53, 124));
        btDisipador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JB/disipador-de-calor.png"))); // NOI18N
        btDisipador.setText("Disipadores");
        btDisipador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btGabinete.setFont(new java.awt.Font("Montserrat", 1, 22)); // NOI18N
        btGabinete.setForeground(new java.awt.Color(37, 53, 124));
        btGabinete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JB/Case.png"))); // NOI18N
        btGabinete.setText("Gabinetes");
        btGabinete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btRam.setFont(new java.awt.Font("Montserrat", 1, 22)); // NOI18N
        btRam.setForeground(new java.awt.Color(37, 53, 124));
        btRam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/JB/memoria-ram.png"))); // NOI18N
        btRam.setText("RAMs");
        btRam.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btProcesador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAlmacenamiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btVentiladores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btTarjetaGrafica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btFuente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btPlacaMadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btDisipador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                    .addComponent(btRam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btGabinete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btRam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btDisipador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btGabinete))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btPlacaMadre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btTarjetaGrafica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btFuente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btProcesador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAlmacenamiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btVentiladores)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregar;
    private javax.swing.JButton btAlmacenamiento;
    private javax.swing.JToggleButton btAtras;
    private javax.swing.JToggleButton btAtrasDlg;
    private javax.swing.JButton btDisipador;
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btFuente;
    private javax.swing.JButton btGabinete;
    private javax.swing.JButton btModificar;
    private javax.swing.JButton btPlacaMadre;
    private javax.swing.JButton btProcesador;
    private javax.swing.JButton btRam;
    private javax.swing.JButton btReporte;
    private javax.swing.JButton btTarjetaGrafica;
    private javax.swing.JButton btVentiladores;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JDialog jdlgCRUD;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
