/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author EDU
 */
public class ModificarAlmacenamiento extends javax.swing.JFrame {

    public JButton getBtnCargardatos() {
        return BtnCargardatos;
    }

    public JToggleButton getBtAtras1() {
        return btAtras1;
    }

    public JButton getBtnBuscarproc() {
        return btnBuscarproc;
    }

    public JButton getBtnCargarImgmodiproc() {
        return btnCargarImgmodiproc;
    }

    public JButton getBtnModificar() {
        return btnModificar;
    }

    public JComboBox<String> getCmbTipo() {
        return cmbTipo;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JSpinner getSpCapacidad() {
        return spCapacidad;
    }

    public JSpinner getSpStock() {
        return spStock;
    }

    public JTable getTblAlmacenamiento() {
        return tblAlmacenamiento;
    }

    public JTextField getTxtIdA() {
        return txtIdA;
    }

    public JTextField getTxtPrecio() {
        return txtPrecio;
    }

    public JTextField getTxtbuscarproc() {
        return txtbuscarproc;
    }

    public JTextField getTxtmarca() {
        return txtmarca;
    }

    public JTextField getTxtmodelo() {
        return txtmodelo;
    }

    public JComboBox<String> getCmbProve() {
        return cmbProve;
    }

    /**
     * Creates new form ModificarAlmacenamiento
     */
    public ModificarAlmacenamiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        txtbuscarproc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCargarImgmodiproc = new javax.swing.JButton();
        btnBuscarproc = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btAtras1 = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtmarca = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtmodelo = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        spCapacidad = new javax.swing.JSpinner();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        spStock = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlmacenamiento = new javax.swing.JTable();
        BtnCargardatos = new javax.swing.JButton();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtIdA = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        cmbProve = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnModificar.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(0, 0, 0));
        btnModificar.setText("Modificar");
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 180, 39));

        txtbuscarproc.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtbuscarproc.setBorder(null);
        jPanel1.add(txtbuscarproc, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 220, 40));

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 20)); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 180, 180));

        btnCargarImgmodiproc.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnCargarImgmodiproc.setForeground(new java.awt.Color(0, 0, 0));
        btnCargarImgmodiproc.setText("Cargar Imagen");
        jPanel1.add(btnCargarImgmodiproc, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 180, 39));

        btnBuscarproc.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnBuscarproc.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarproc.setText("Buscar");
        jPanel1.add(btnBuscarproc, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 120, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 212, 250), 3));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(37, 53, 124));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        jLabel20.setText("Almacenamiento");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 3, 560, 100));

        btAtras1.setBackground(new java.awt.Color(255, 255, 255));
        btAtras1.setFont(new java.awt.Font("Montserrat Black", 1, 48)); // NOI18N
        btAtras1.setForeground(new java.awt.Color(0, 212, 250));
        btAtras1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        jPanel4.add(btAtras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, -1, 100));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 110));

        jLabel11.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("_______________");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, 20));

        jLabel12.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("_______________");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, 20));

        jLabel13.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("_______________");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, 20));

        jLabel14.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("_______________");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, 20));

        jLabel30.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel30.setText("Marca:");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, 40));

        txtmarca.setBackground(new java.awt.Color(255, 255, 255));
        txtmarca.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtmarca.setForeground(new java.awt.Color(0, 0, 0));
        txtmarca.setBorder(null);
        jPanel1.add(txtmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 150, 40));

        jLabel31.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel31.setText("Modelo:");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 110, 40));

        txtmodelo.setBackground(new java.awt.Color(255, 255, 255));
        txtmodelo.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtmodelo.setForeground(new java.awt.Color(0, 0, 0));
        txtmodelo.setBorder(null);
        jPanel1.add(txtmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 150, 40));

        jLabel32.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel32.setText("Tipo");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 110, 40));

        jLabel33.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel33.setText("Capacidad:");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 110, 40));

        spCapacidad.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jPanel1.add(spCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 60, 40));

        jLabel34.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel34.setText("Precio:");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, 40));

        jLabel36.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel36.setText("Stock:");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 110, 40));

        spStock.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jPanel1.add(spStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 60, 40));

        tblAlmacenamiento.setAutoCreateRowSorter(true);
        tblAlmacenamiento.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        tblAlmacenamiento.setForeground(new java.awt.Color(0, 0, 0));
        tblAlmacenamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Almacenamiento", "Marca", "Modelo", "Tipo", "Capacidad", "Precio", "Proveedor", "Stock"
            }
        ));
        jScrollPane1.setViewportView(tblAlmacenamiento);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 640, 400));

        BtnCargardatos.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        BtnCargardatos.setForeground(new java.awt.Color(0, 0, 0));
        BtnCargardatos.setText("Cargar Datos");
        jPanel1.add(BtnCargardatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 180, 40));

        cmbTipo.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SDD", "HDD", "M2" }));
        jPanel1.add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 150, 40));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, 40));

        txtIdA.setBackground(new java.awt.Color(255, 255, 255));
        txtIdA.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtIdA.setForeground(new java.awt.Color(0, 0, 0));
        txtIdA.setBorder(null);
        jPanel1.add(txtIdA, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 150, 40));

        txtPrecio.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecio.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(0, 0, 0));
        txtPrecio.setBorder(null);
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 150, 40));

        jLabel35.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel35.setText("Proveedor:");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 110, 40));

        cmbProve.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jPanel1.add(cmbProve, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCargardatos;
    private javax.swing.JToggleButton btAtras1;
    private javax.swing.JButton btnBuscarproc;
    private javax.swing.JButton btnCargarImgmodiproc;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbProve;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spCapacidad;
    private javax.swing.JSpinner spStock;
    private javax.swing.JTable tblAlmacenamiento;
    private javax.swing.JTextField txtIdA;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtbuscarproc;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmodelo;
    // End of variables declaration//GEN-END:variables
}
