/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author MAX COMPUTERS
 */
public class ModificarProcesador extends javax.swing.JFrame {

    /**
     * Creates new form ModificarProcesador
     */
    public ModificarProcesador() {
        initComponents();
    }

    public JToggleButton getBtAtras1() {
        return btAtras1;
    }

    public void setBtAtras1(JToggleButton btAtras1) {
        this.btAtras1 = btAtras1;
    }

    public JButton getBtnBuscarproc() {
        return btnBuscarproc;
    }

    public void setBtnBuscarproc(JButton btnBuscarproc) {
        this.btnBuscarproc = btnBuscarproc;
    }

    public JButton getBtnCargarImgmodiproc() {
        return btnCargarImgmodiproc;
    }

    public void setBtnCargarImgmodiproc(JButton btnCargarImgmodiproc) {
        this.btnCargarImgmodiproc = btnCargarImgmodiproc;
    }

    public JButton getBtnModificarproc() {
        return btnModificarproc;
    }

    public void setBtnModificarproc(JButton btnModificarproc) {
        this.btnModificarproc = btnModificarproc;
    }

    public JComboBox<String> getCbproveedormodiproc() {
        return cbproveedormodiproc;
    }

    public void setCbproveedormodiproc(JComboBox<String> cbproveedormodiproc) {
        this.cbproveedormodiproc = cbproveedormodiproc;
    }

    public JLabel getLbIdmodiproc() {
        return lbIdmodiproc;
    }

    public void setLbIdmodiproc(JLabel lbIdmodiproc) {
        this.lbIdmodiproc = lbIdmodiproc;
    }

    public JLabel getLbimagenproce() {
        return lbimagenproce;
    }

    public void setLbimagenproce(JLabel lbimagenproce) {
        this.lbimagenproce = lbimagenproce;
    }

    public JSpinner getSpRammodiproc() {
        return spRammodiproc;
    }

    public void setSpRammodiproc(JSpinner spRammodiproc) {
        this.spRammodiproc = spRammodiproc;
    }

    public JSpinner getSpWattsmodiproc() {
        return spWattsmodiproc;
    }

    public void setSpWattsmodiproc(JSpinner spWattsmodiproc) {
        this.spWattsmodiproc = spWattsmodiproc;
    }

    public JSpinner getSpnucleosmodiproc() {
        return spnucleosmodiproc;
    }

    public void setSpnucleosmodiproc(JSpinner spnucleosmodiproc) {
        this.spnucleosmodiproc = spnucleosmodiproc;
    }

    public JTable getTbprocesadores() {
        return tbprocesadores;
    }

    public void setTbprocesadores(JTable tbprocesadores) {
        this.tbprocesadores = tbprocesadores;
    }

    public JTextField getTxtbuscarproc() {
        return txtbuscarproc;
    }

    public void setTxtbuscarproc(JTextField txtbuscarproc) {
        this.txtbuscarproc = txtbuscarproc;
    }

    public JTextField getTxtghzmodiproc() {
        return txtghzmodiproc;
    }

    public void setTxtghzmodiproc(JTextField txtghzmodiproc) {
        this.txtghzmodiproc = txtghzmodiproc;
    }

    public JTextField getTxtmarcamodiproc() {
        return txtmarcamodiproc;
    }

    public void setTxtmarcamodiproc(JTextField txtmarcamodiproc) {
        this.txtmarcamodiproc = txtmarcamodiproc;
    }

    public JTextField getTxtmodelomodiproc() {
        return txtmodelomodiproc;
    }

    public void setTxtmodelomodiproc(JTextField txtmodelomodiproc) {
        this.txtmodelomodiproc = txtmodelomodiproc;
    }

    public JTextField getTxtpreciomodiproc() {
        return txtpreciomodiproc;
    }

    public void setTxtpreciomodiproc(JTextField txtpreciomodiproc) {
        this.txtpreciomodiproc = txtpreciomodiproc;
    }

    public JTextField getTxtsocketmodiproc() {
        return txtsocketmodiproc;
    }

    public void setTxtsocketmodiproc(JTextField txtsocketmodiproc) {
        this.txtsocketmodiproc = txtsocketmodiproc;
    }

    public JTextField getTxtstockmodiproc() {
        return txtstockmodiproc;
    }

    public void setTxtstockmodiproc(JTextField txtstockmodiproc) {
        this.txtstockmodiproc = txtstockmodiproc;
    }

    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnModificarproc = new javax.swing.JButton();
        txtbuscarproc = new javax.swing.JTextField();
        txtsocketmodiproc = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        spRammodiproc = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        spWattsmodiproc = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        txtpreciomodiproc = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbIdmodiproc = new javax.swing.JLabel();
        lbimagenproce = new javax.swing.JLabel();
        btnCargarImgmodiproc = new javax.swing.JButton();
        cbproveedormodiproc = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txtmarcamodiproc = new javax.swing.JTextField();
        btnBuscarproc = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtmodelomodiproc = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtghzmodiproc = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbprocesadores = new javax.swing.JTable();
        spnucleosmodiproc = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btAtras1 = new javax.swing.JToggleButton();
        jLabel36 = new javax.swing.JLabel();
        txtstockmodiproc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnModificarproc.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnModificarproc.setText("Modificar");

        txtbuscarproc.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtbuscarproc.setBorder(null);

        txtsocketmodiproc.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtsocketmodiproc.setBorder(null);

        jLabel21.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Máximo Ram:");
        jLabel21.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        spRammodiproc.setFont(new java.awt.Font("Montserrat Thin", 0, 18)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Watts:");
        jLabel22.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        spWattsmodiproc.setFont(new java.awt.Font("Montserrat Thin", 0, 18)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Proveedor:");
        jLabel23.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtpreciomodiproc.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtpreciomodiproc.setBorder(null);

        jLabel24.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Precio:");
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel14.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("ID Procesador:");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lbIdmodiproc.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lbIdmodiproc.setText("--");
        lbIdmodiproc.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lbimagenproce.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCargarImgmodiproc.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnCargarImgmodiproc.setText("Cargar Imagen");

        cbproveedormodiproc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Marca:");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtmarcamodiproc.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtmarcamodiproc.setBorder(null);

        btnBuscarproc.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        btnBuscarproc.setText("Buscar");

        jLabel16.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Modelo:");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtmodelomodiproc.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtmodelomodiproc.setBorder(null);

        jLabel17.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel17.setText("Núcleos Físicos:");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtghzmodiproc.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtghzmodiproc.setBorder(null);

        jLabel18.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("GHz:");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        tbprocesadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Procesador", "Marca", "Modelo", "Núcleos Físicos", "GHz", "Socket", "Máximo Ram", "Watts", "Precio", "Stock", "Proveedor"
            }
        ));
        jScrollPane1.setViewportView(tbprocesadores);

        spnucleosmodiproc.setFont(new java.awt.Font("Montserrat Thin", 0, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Socket:");
        jLabel19.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 212, 250), 3));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(37, 53, 124));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        jLabel20.setText("Procesadores");

        btAtras1.setBackground(new java.awt.Color(255, 255, 255));
        btAtras1.setFont(new java.awt.Font("Montserrat Black", 1, 48)); // NOI18N
        btAtras1.setForeground(new java.awt.Color(0, 212, 250));
        btAtras1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btAtras1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btAtras1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel36.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel36.setText("Stock:");
        jLabel36.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtstockmodiproc.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        txtstockmodiproc.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btnModificarproc))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtmarcamodiproc, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtmodelomodiproc, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(97, 97, 97)
                                .addComponent(spnucleosmodiproc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtghzmodiproc, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtsocketmodiproc, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(spRammodiproc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(spWattsmodiproc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(lbIdmodiproc, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(cbproveedormodiproc, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtstockmodiproc, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(10, 10, 10)
                                            .addComponent(txtpreciomodiproc, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lbimagenproce, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCargarImgmodiproc)
                                .addGap(55, 55, 55)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscarproc)
                        .addGap(10, 10, 10)
                        .addComponent(txtbuscarproc, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(lbIdmodiproc))
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCargarImgmodiproc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(txtmarcamodiproc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(txtmodelomodiproc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(spnucleosmodiproc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(txtghzmodiproc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(txtsocketmodiproc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(spRammodiproc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(spWattsmodiproc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(txtpreciomodiproc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel36)
                                    .addComponent(txtstockmodiproc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(cbproveedormodiproc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbimagenproce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addComponent(btnModificarproc))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarproc)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(txtbuscarproc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btAtras1;
    private javax.swing.JButton btnBuscarproc;
    private javax.swing.JButton btnCargarImgmodiproc;
    private javax.swing.JButton btnModificarproc;
    private javax.swing.JComboBox<String> cbproveedormodiproc;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbIdmodiproc;
    private javax.swing.JLabel lbimagenproce;
    private javax.swing.JSpinner spRammodiproc;
    private javax.swing.JSpinner spWattsmodiproc;
    private javax.swing.JSpinner spnucleosmodiproc;
    private javax.swing.JTable tbprocesadores;
    private javax.swing.JTextField txtbuscarproc;
    private javax.swing.JTextField txtghzmodiproc;
    private javax.swing.JTextField txtmarcamodiproc;
    private javax.swing.JTextField txtmodelomodiproc;
    private javax.swing.JTextField txtpreciomodiproc;
    private javax.swing.JTextField txtsocketmodiproc;
    private javax.swing.JTextField txtstockmodiproc;
    // End of variables declaration//GEN-END:variables
}
